//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ufanet
{
    using System;
    using System.Collections.Generic;
    
    public partial class balances
    {
        public int balance_id { get; set; }
        public int subscriber_id { get; set; }
        public Nullable<decimal> current_balance { get; set; }
    
        public virtual subscribers subscribers { get; set; }
    }
}
