//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ufanet
{
    using System;
    using System.Collections.Generic;
    
    public partial class connections
    {
        public int connection_id { get; set; }
        public int tariff_id { get; set; }
        public int subscriber_id { get; set; }
        public Nullable<System.DateTime> connection_date { get; set; }
        public string status { get; set; }
    
        public virtual subscribers subscribers { get; set; }
        public virtual tariffs tariffs { get; set; }
    }
}
